JAVA_HOME=/usr/local/java17/java-17-openjdk-17.0.10.0.7-1.portable.jdk.el.x86_64
JAVA_OPTS="-classpath .:/usr/share/java/gdal.jar -Djava.library.path=/usr/lib/jni"
RUN_ARGS="--spring.config.location=/opt/mobility-integration-manage/application-ct.yml,/opt/drone-domain-api-service/application-ct.yml --logging.config=/opt/drone-domain-api-service/logback.xml"
